const HTTP_STATUS_CODE_BAD_REQUEST = 400;
const HTTP_STATUS_CODE_BAD_GATEWAY = 502;

const ERROR_EMAIL_EXISTS = 'EMAIL_EXISTS';
const ERROR_EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
const ERROR_WALLET_NOT_FOUND = 'WALLET_NOT_FOUND';
const ERROR_WALLET_EXISTS = 'WALLET_EXISTS';
const ERROR_BAD_SIGNATURE = 'BAD_SIGNATURE';
const ERROR_BAD_AUTH = 'BAD_AUTH';
const ERROR_BAD_PARAMS = 'BAD_PARAMS';
const ERROR_BAD_EMAIL_OR_PASSWORD = 'BAD_EMAIL_OR_PASSWORD';
const ERROR_PASSWORDS_DOES_NOT_MATCH = 'PASSWORDS_DOES_NOT_MATCH';
const ERROR_ALREADY_FAVOURITE = 'ALREADY_FAVOURITE';
const ERROR_NOT_A_FAVOURITE = 'NOT_A_FAVOURITE';

module.exports = {
    ERROR_EMAIL_EXISTS,
    ERROR_EMAIL_NOT_FOUND,
    ERROR_WALLET_NOT_FOUND,
    ERROR_WALLET_EXISTS,
    ERROR_BAD_SIGNATURE,
    ERROR_BAD_AUTH,
    ERROR_BAD_PARAMS,
    ERROR_BAD_EMAIL_OR_PASSWORD,
    ERROR_PASSWORDS_DOES_NOT_MATCH,
    ERROR_ALREADY_FAVOURITE,
    ERROR_NOT_A_FAVOURITE,
    HTTP_STATUS_CODE_BAD_REQUEST,
    HTTP_STATUS_CODE_BAD_GATEWAY
};